import argparse

import os
import json
import numpy as np

from tqdm import tqdm
from utils import *
from visualization.visualization import visualization_mllm_with_object

def parse_args():
    parser = argparse.ArgumentParser(description='Faithfulness Metric')
    parser.add_argument('--explanation-dir', 
                        type=str, 
                        default='interpretation_results/Qwen2.5-VL-3B-coco-object/slico-1.0-1.0-division-number-64',
                        help='Save path for saliency maps generated by our methods.')
    parser.add_argument('--Datasets',
                        type=str,
                        default='datasets/coco/val2017',
                        help='Datasets.')
    args = parser.parse_args()
    return args

def main(args):
    print(args.explanation_dir)
    
    json_root_file = os.path.join(args.explanation_dir, "json")
    npy_root_file = os.path.join(args.explanation_dir, "npy")
    
    full_visualization_path = os.path.join(args.explanation_dir, "visualization")
    mkdir(full_visualization_path)
    
    json_file_names = os.listdir(json_root_file)
    for json_file_name in tqdm(json_file_names):
        json_file_path = os.path.join(json_root_file, json_file_name)
        npy_file_path = os.path.join(npy_root_file, json_file_name.replace(".json", ".npy"))
        
        image_path = os.path.join(args.Datasets, 
                                      json_file_name.replace(".json", ".jpg"))
        
        save_full_visualization_map_path = os.path.join(full_visualization_path, json_file_name.replace(".json", ".png"))
        if os.path.exists(save_full_visualization_map_path):
            continue
        
        with open(json_file_path, 'r', encoding='utf-8') as f:
            saved_json_file = json.load(f)
        S_set = np.load(npy_file_path)
        
        visualization_mllm_with_object(image_path, S_set, saved_json_file, save_path=save_full_visualization_map_path)
        
if __name__ == "__main__":
    args = parse_args()
    main(args)
        